services:
    bank.user:
        image: bank.user
        build:
            context: ..
            dockerfile: Scripts/User/Dockerfile
        env_file:
            - user.env
        ports:
            - "${EXPOSE_PORT}:8080"
        depends_on:
            - database
    database:
        image: postgres:latest
        env_file:
            - database.env
        ports:
            - "${EXPOSE_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    postgres_data:
